/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.20
 * Generated at: 2017-09-19 08:25:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import work.model.dto.Bmember;

public final class Service_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("work.model.dto.Bmember");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>service</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function btn_infor(){\r\n");
      out.write("\tdocument.servicepage.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form name=\"servicepage\" method=\"post\" action=\"controller\">\r\n");
      out.write("\t\t<table border=\"1\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>user</td>\r\n");
      out.write("\t\t\t\t<td>");
      out.print( session.getAttribute("userId") );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" onclick=\"btn_idSearch()\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" value=\"infor\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\"  value=\"회원 정보 호출\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<a href=\"controller?action=logout\">로그아웃</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("\t<form name=\"modiForm\" action=\"controller\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t");

				Bmember dto = (Bmember)request.getAttribute("Information");
				if (dto != null){
			
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>아이디</span></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( dto.getmId() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>비밀번호</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"moPw\" value=");
      out.print( dto.getmPw().substring(0, 2)+"****" );
      out.write(">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>이름</span></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( dto.getmName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>닉네임</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"moPw\" value=");
      out.print( dto.getmNick() );
      out.write(">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>생일</span></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( dto.getmBirth() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>번호</span></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( dto.getmPhone() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>이메일</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");

							String[] str = dto.getmMail().split("@");
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"moEmail\" value=\"");
      out.print( str[0].trim() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t@  <input type=\"text\" name=\"moEmail2\" size=\"10\">\r\n");
      out.write("\t\t\t\t\t\t<select name=\"moDomain\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>::::::: 선택 :::::::</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>chol.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>daum.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>dreamwiz.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>empal.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>hanmir.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>hanafos.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>hotmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>lycos.co.kr</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>paran.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>yahoo.co.kr</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option>직접입력</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\tvar takeDomain = document.modiForm.moDomain;\r\n");
      out.write("\t\t\t\t\t\t\tvar inputDomain = document.modiForm.moDomain;\r\n");
      out.write("\t\t\t\t\t\t\tif (takeDomain.options == \"");
      out.print( str[1].trim() );
      out.write("\"){\r\n");
      out.write("\t\t\t\t\t\t\t\ttakeDomain.value = ");
      out.print( str[1].trim() );
      out.write(";\r\n");
      out.write("\t\t\t\t\t\t\t\tinputDomain.value = ");
      out.print( str[1].trim() );
      out.write(";\r\n");
      out.write("\t\t\t\t\t\t\t\tinputDomain.readOnly=true;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\ttakeDomain.value = \"직접입력\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinputDomain.value = ");
      out.print( str[1].trim() );
      out.write(";\r\n");
      out.write("\t\t\t\t\t\t\t\tinputDomain.readOnly=true;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tdocument.modiForm.moDomain.value=");
      out.print( dto.getmQuest() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\tdomain : ");
      out.print( str[1].trim() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\tall : ");
      out.print( dto.getmMail() );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>성별</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"moGender\" value=\"M\">남성\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"moGender\" value=\"F\">여성\r\n");
      out.write("\t\t\t\t\t\t<script>\r\n");
      out.write("\t\t\t\t\t\t\tvar takeElement = document.modiForm.moGender;\r\n");
      out.write("\t\t\t\t\t\t\tfor (var i=0; i< takeElement.length; i++){\r\n");
      out.write("\t\t\t\t\t\t\t\tif (takeElement[i].value == \"");
      out.print( dto.getmGender() );
      out.write("\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttakeElement[i].click();\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>주소</span></td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print( dto.getmAddress() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>질문</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select name=\"moQuestion\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">기억에 남는 추억의 장소는?</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">존경하는 인물은?</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">좋아하는 물건은?</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4\">좋아하는 글귀는?</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5\">하고싶지 않은일 할 때 하는 표정은?</option>\r\n");
      out.write("\t\t\t\t\t\t<script>document.modiForm.rQuestion.value=");
      out.print( dto.getmQuest() );
      out.write("</script>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><span>답변</span></td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"moAnswer\" value=");
      out.print( dto.getmAnswer() );
      out.write(">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"변경\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
